# Pandas: практика

**Автор:** _имя_ · **Модуль:** Pandas

Блоки 1–6 — на маленькой таблице заказов, блок 7 — мини-анализ открытого датасета поездок такси Нью-Йорка (6 433 строки). После каждого блока — короткий вывод: что сделано и что удалось узнать о данных.

In [4]:
from pathlib import Path

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 30)
pd.set_option("display.width", 140)
print("pandas", pd.__version__)

pandas 3.1.0

## 1. Series и DataFrame

Таблица из десяти заказов: order_id, customer, city, category, price, quantity, order_date.

- создай таблицу сначала из словаря, затем из списка словарей
- изучи `shape`, `columns`, `index` и `dtypes`
- выведи первые и последние строки
- выбери один столбец как Series и несколько столбцов как DataFrame
- переименуй два столбца и измени порядок колонок
- добавь новый заказ и удали одну строку

In [5]:
# блок 1
# 1.1 из словаря: ключ — название столбца, значение — список значений этого столбца
orders_dict = {
    "order_id":   [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "customer":   ["Анна", "Борис", "Вера", "Глеб", "Анна", "Дина", "Борис", "Елена", "Вера", "Глеб"],
    "city":       ["Москва", "Казань", "Москва", "Самара", "Москва", "Казань", "Казань", "Самара", "Москва", "Самара"],
    "category":   ["Электроника", "Книги", "Одежда", "Электроника", "Книги", "Одежда", "Электроника", "Книги", "Электроника", "Одежда"],
    "price":      [25000, 800, 3500, 12000, 650, 4200, 18000, 1200, 9000, 2800],
    "quantity":   [1, 3, 2, 1, 4, 1, 2, 2, 1, 3],
    "order_date": ["2026-09-05", "2026-09-07", "2026-09-12", "2026-09-15", "2026-09-20",
                   "2026-09-23", "2026-09-27", "2026-10-01", "2026-10-04", "2026-10-08"],
}
df_from_dict = pd.DataFrame(orders_dict)

# 1.2 из списка словарей: один словарь — одна строка (как транзакции в трекере расходов)
orders_list = [
    {"order_id": 101, "customer": "Анна",  "city": "Москва", "category": "Электроника", "price": 25000, "quantity": 1, "order_date": "2026-09-05"},
    {"order_id": 102, "customer": "Борис", "city": "Казань", "category": "Книги",       "price": 800,   "quantity": 3, "order_date": "2026-09-07"},
    {"order_id": 103, "customer": "Вера",  "city": "Москва", "category": "Одежда",      "price": 3500,  "quantity": 2, "order_date": "2026-09-12"},
    {"order_id": 104, "customer": "Глеб",  "city": "Самара", "category": "Электроника", "price": 12000, "quantity": 1, "order_date": "2026-09-15"},
    {"order_id": 105, "customer": "Анна",  "city": "Москва", "category": "Книги",       "price": 650,   "quantity": 4, "order_date": "2026-09-20"},
    {"order_id": 106, "customer": "Дина",  "city": "Казань", "category": "Одежда",      "price": 4200,  "quantity": 1, "order_date": "2026-09-23"},
    {"order_id": 107, "customer": "Борис", "city": "Казань", "category": "Электроника", "price": 18000, "quantity": 2, "order_date": "2026-09-27"},
    {"order_id": 108, "customer": "Елена", "city": "Самара", "category": "Книги",       "price": 1200,  "quantity": 2, "order_date": "2026-10-01"},
    {"order_id": 109, "customer": "Вера",  "city": "Москва", "category": "Электроника", "price": 9000,  "quantity": 1, "order_date": "2026-10-04"},
    {"order_id": 110, "customer": "Глеб",  "city": "Самара", "category": "Одежда",      "price": 2800,  "quantity": 3, "order_date": "2026-10-08"},
]
df = pd.DataFrame(orders_list)
print("таблицы одинаковые:", df.equals(df_from_dict))

# 1.3 устройство таблицы
print("\nshape:", df.shape)
print("columns:", df.columns.tolist())
print("index:", df.index)
print("\ndtypes:"); print(df.dtypes)

# 1.4 первые и последние строки
display(df.head(3))
display(df.tail(2))

# 1.5 один столбец → Series, несколько → DataFrame
city = df["city"]
two_cols = df[["customer", "price"]]
print(type(city).__name__, city.shape, "|", type(two_cols).__name__, two_cols.shape)

# 1.6 переименовать два столбца и поменять порядок колонок (на копии, df не трогаем)
demo = df.rename(columns={"customer": "client", "order_date": "date"})
demo = demo[["order_id", "date", "client", "city", "category", "price", "quantity"]]
print(demo.columns.tolist())

# 1.7 добавить заказ и удалить строку
new_order = pd.DataFrame([{"order_id": 111, "date": "2026-10-10", "client": "Жанна", "city": "Пермь",
                           "category": "Книги", "price": 950, "quantity": 2}])
demo = pd.concat([demo, new_order], ignore_index=True)
demo = demo[demo["order_id"] != 105]            # удалить заказ 105: оставляем всё, кроме него
print("строк в demo:", len(demo), "| заказ 111 есть:", 111 in demo["order_id"].values, "| 105 нет:", 105 not in demo["order_id"].values)
display(demo.tail(3))

# рабочая таблица для блоков 2–6: номер заказа — в индекс
orders = df.set_index("order_id")
display(orders.head(3))

таблицы одинаковые: True

shape: (10, 7)
columns: ['order_id', 'customer', 'city', 'category', 'price', 'quantity', 'order_date']
index: RangeIndex(start=0, stop=10, step=1)

dtypes:
order_id      int64
customer        str
city            str
category        str
price         int64
quantity      int64
order_date      str
dtype: object

   order_id customer    city     category  price  quantity  order_date
0       101     Анна  Москва  Электроника  25000         1  2026-09-05
1       102    Борис  Казань        Книги    800         3  2026-09-07
2       103     Вера  Москва       Одежда   3500         2  2026-09-12

   order_id customer    city     category  price  quantity  order_date
8       109     Вера  Москва  Электроника   9000         1  2026-10-04
9       110     Глеб  Самара       Одежда   2800         3  2026-10-08

Series (10,) | DataFrame (10, 2)
['order_id', 'date', 'client', 'city', 'category', 'price', 'quantity']
строк в demo: 10 | заказ 111 есть: True | 105 нет: True

    order_id        date client    city     category  price  quantity
8        109  2026-10-04   Вера  Москва  Электроника   9000         1
9        110  2026-10-08   Глеб  Самара       Одежда   2800         3
10       111  2026-10-10  Жанна   Пермь        Книги    950         2

         customer    city     category  price  quantity  order_date
order_id
101          Анна  Москва  Электроника  25000         1  2026-09-05
102         Борис  Казань        Книги    800         3  2026-09-07
103          Вера  Москва       Одежда   3500         2  2026-09-12

### Вывод по блоку 1

...

## 2. Выбор данных и фильтрация


- выбери строки по индексам через `loc` и по позициям через `iloc`
- найди заказы дороже заданной суммы
- выбери заказы из нескольких городов через `isin`
- отфильтруй строки сразу по нескольким условиям
- найди товары, название категории которых содержит заданную подстроку
- отсортируй данные сначала по цене, затем по количеству
- выбери три заказа с максимальной итоговой стоимостью

In [6]:
# блок 2

### Вывод по блоку 2

...

## 3. Очистка данных

Намеренно добавляем пропуски, дубликаты, отрицательную цену и даты в неправильном формате.

- найди количество пропусков в каждом столбце
- выбери подходящую стратегию заполнения или удаления пропусков
- найди и удали полные и частичные дубликаты
- преобразуй числовые столбцы и даты в правильные типы
- обнаружь некорректные значения и исправь либо исключи их
- сравни размер и статистики таблицы до и после очистки
- объясни, почему очистку важно выполнять до анализа и обучения модели

In [7]:
# блок 3

### Вывод по блоку 3

...

## 4. Новые признаки и преобразования


- создай столбец `total_price = price × quantity`
- выдели из даты год, месяц, день недели и признак выходного дня
- разбей стоимость заказа на категории low, medium и high через `pd.cut`
- приведи строковые значения к единому регистру и убери лишние пробелы
- создай признак длины имени клиента
- используй `map`, `replace` и `assign` минимум по одному разу
- сравни обычный `apply` с векторизованной операцией

In [8]:
# блок 4

### Вывод по блоку 4

...

## 5. GroupBy и агрегации


- посчитай сумму и средний чек по городам
- найди количество заказов и уникальных клиентов по категориям
- рассчитай сразу несколько статистик через `agg`
- найди самый дорогой заказ внутри каждой категории
- добавь к каждой строке среднюю стоимость заказа её категории через `transform`
- вычисли долю каждого заказа в общей выручке своего города
- отсортируй группы по выручке и сформулируй минимум три вывода

In [9]:
# блок 5

### Вывод по блоку 5

...

## 6. Объединение таблиц и сводные таблицы

Отдельные таблицы customers и products, в заказах — только идентификаторы.

- объедини таблицы через `merge`
- сравни результаты inner, left и outer join
- найди строки, для которых не нашлось соответствия в другой таблице
- объедини две таблицы с одинаковой структурой через `concat`
- построй pivot table с выручкой по городам и категориям
- добавь итоги по строкам и столбцам
- преобразуй широкую таблицу в длинную через `melt`

In [10]:
# блок 6

### Вывод по блоку 6

...

## 7. Мини-анализ датасета: такси Нью-Йорка

Открытый датасет `taxis.csv` из seaborn-data: 6 433 поездки за март 2019 года.

- загрузи данные и проведи первичный обзор
- составь таблицу: признак, тип, количество пропусков, число уникальных значений
- очисти данные и обоснуй каждое изменение
- сформулируй пять вопросов к датасету и ответь на них с помощью фильтрации и groupby
- создай минимум три полезных новых признака
- используй merge или pivot_table хотя бы один раз
- сохрани очищенную таблицу в новый CSV без лишнего индекса
- сформулируй не менее пяти содержательных выводов о данных

In [11]:
# блок 7

### Вывод по блоку 7

...

## Перед сдачей

- [ ] `Restart` → `Run All` проходит без ошибок
- [ ] после каждого блока есть вывод своими словами
- [ ] очищенный CSV сохранён в `data/`